-- Litera library schema. Safe to re-run against an existing project.

create table if not exists public.buku (
  id bigint generated by default as identity primary key,
  judul text not null,
  stok integer not null default 0 check (stok >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  borrower_id uuid references auth.users(id) on delete set null,
  item_id bigint not null references public.buku(id) on delete cascade,
  qty integer not null default 1 check (qty > 0),
  status text not null default 'sedang dipinjam'
    check (status in ('sedang dipinjam', 'sudah dikembalikan', 'terkena denda')),
  created_at timestamptz not null default now()
);

alter table public.transactions
  add column if not exists borrower_id uuid references auth.users(id) on delete set null;

alter table public.transactions
  drop constraint if exists transactions_item_id_fkey;
alter table public.transactions
  add constraint transactions_item_id_fkey
  foreign key (item_id) references public.buku(id) on delete cascade;

update public.transactions
set status = 'sudah dikembalikan'
where lower(trim(status)) in ('selesai', 'returned', 'dikembalikan', 'completed');

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'buku_stok_check' and conrelid = 'public.buku'::regclass) then
    alter table public.buku add constraint buku_stok_check check (stok >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'transactions_qty_check' and conrelid = 'public.transactions'::regclass) then
    alter table public.transactions add constraint transactions_qty_check check (qty > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'transactions_status_check' and conrelid = 'public.transactions'::regclass) then
    alter table public.transactions add constraint transactions_status_check
      check (status in ('sedang dipinjam', 'sudah dikembalikan', 'terkena denda'));
  end if;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default 'Anggota',
  role text not null default 'anggota' check (role in ('admin', 'anggota')),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text not null default 'Anggota';
alter table public.profiles add column if not exists role text not null default 'anggota';
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

update public.profiles
set role = case when role = 'admin' then 'admin' else 'anggota' end
where role is null or role not in ('admin', 'anggota');
alter table public.profiles alter column role set default 'anggota';
alter table public.profiles alter column role set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_role_check' and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_role_check check (role in ('admin', 'anggota'));
  end if;
end;
$$;

create index if not exists transactions_borrower_id_idx on public.transactions(borrower_id);
create index if not exists transactions_created_at_idx on public.transactions(created_at desc);
create index if not exists buku_judul_idx on public.buku(judul);

insert into public.buku (judul, stok)
select seed.judul, seed.stok
from (values
  ('Buku Sains Dasar', 10),
  ('Buku Fiksi Populer', 8),
  ('Buku Teknologi', 12)
) as seed(judul, stok)
where not exists (
  select 1 from public.buku existing where existing.judul = seed.judul
);

insert into public.profiles (id, full_name, role)
select
  users.id,
  coalesce(nullif(trim(users.raw_user_meta_data ->> 'full_name'), ''), split_part(coalesce(users.email, 'Anggota'), '@', 1)),
  'anggota'
from auth.users users
on conflict (id) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(coalesce(new.email, 'Anggota'), '@', 1)),
    'anggota'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create or replace function public.proses_transaksi(
  p_customer_name text,
  p_item_id bigint,
  p_qty integer
)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_stok integer;
  v_customer_name text;
begin
  if auth.uid() is null then
    raise exception 'Silakan masuk untuk meminjam buku';
  end if;
  if p_qty is null or p_qty < 1 then
    raise exception 'Jumlah peminjaman harus lebih dari 0';
  end if;

  select full_name into v_customer_name
  from public.profiles where id = auth.uid();
  if v_customer_name is null then
    raise exception 'Profil anggota tidak ditemukan';
  end if;

  select stok into v_stok
  from public.buku
  where id = p_item_id
  for update;
  if v_stok is null then
    raise exception 'Buku tidak ditemukan';
  end if;
  if p_qty > v_stok then
    raise exception 'Stok tidak cukup';
  end if;

  update public.buku set stok = stok - p_qty where id = p_item_id;
  insert into public.transactions (customer_name, borrower_id, item_id, qty, status)
  values (v_customer_name, auth.uid(), p_item_id, p_qty, 'sedang dipinjam');

  return json_build_object(
    'status', 'success',
    'customer_name', v_customer_name,
    'item_id', p_item_id,
    'qty', p_qty
  );
end;
$$;

create or replace function public.set_transaction_status(
  p_transaction_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item_id bigint;
  v_qty integer;
  v_current_status text;
begin
  if not public.is_admin() then
    raise exception 'Aksi ini hanya tersedia untuk administrator';
  end if;
  if p_status not in ('sudah dikembalikan', 'terkena denda') then
    raise exception 'Status transaksi tidak valid';
  end if;

  select item_id, qty, status
  into v_item_id, v_qty, v_current_status
  from public.transactions
  where id = p_transaction_id
  for update;
  if not found then
    raise exception 'Transaksi tidak ditemukan';
  end if;
  if v_current_status = p_status then
    return;
  end if;
  if v_current_status <> 'sedang dipinjam' then
    raise exception 'Status transaksi ini sudah final';
  end if;

  if p_status = 'sudah dikembalikan' then
    update public.buku set stok = stok + v_qty where id = v_item_id;
  end if;
  update public.transactions set status = p_status where id = p_transaction_id;
end;
$$;

alter table public.buku enable row level security;
alter table public.transactions enable row level security;
alter table public.profiles enable row level security;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public' and tablename in ('buku', 'transactions', 'profiles')
  loop
    execute format('drop policy if exists %I on public.%I', existing_policy.policyname, existing_policy.tablename);
  end loop;
end;
$$;

create policy buku_read_catalog on public.buku
  for select to anon, authenticated using (true);
create policy buku_write_authenticated on public.buku
  for insert to authenticated with check ((select public.is_admin()));
create policy buku_update_authenticated on public.buku
  for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
create policy buku_delete_admin on public.buku
  for delete to authenticated using ((select public.is_admin()));

create policy transactions_read_authenticated on public.transactions
  for select to authenticated
  using ((select public.is_admin()) or borrower_id = (select auth.uid()));
create policy transactions_delete_admin on public.transactions
  for delete to authenticated using ((select public.is_admin()));

create policy profiles_read_self_or_admin on public.profiles
  for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));
create policy profiles_update_admin on public.profiles
  for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

grant usage on schema public to anon, authenticated;
revoke all on public.buku, public.transactions, public.profiles from anon, authenticated;
grant select on public.buku to anon, authenticated;
grant insert, update, delete on public.buku to authenticated;
grant select, delete on public.transactions to authenticated;
grant select, update on public.profiles to authenticated;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;
revoke all on function public.proses_transaksi(text, bigint, integer) from public, anon;
grant execute on function public.proses_transaksi(text, bigint, integer) to authenticated;
revoke all on function public.set_transaction_status(bigint, text) from public, anon;
grant execute on function public.set_transaction_status(bigint, text) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'buku') then
      execute 'alter publication supabase_realtime add table public.buku';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'transactions') then
      execute 'alter publication supabase_realtime add table public.transactions';
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'profiles') then
      execute 'alter publication supabase_realtime add table public.profiles';
    end if;
  end if;
end;
$$;

-- Bootstrap an administrator once in the Supabase SQL Editor.
-- Replace the email and display name with the target auth.users account.
-- insert into public.profiles (id, full_name, role)
-- select id, 'Nama Admin', 'admin' from auth.users where email = 'admin@example.com'
-- on conflict (id) do update set full_name = excluded.full_name, role = 'admin', updated_at = now();
