-- =====================================================
-- Litera Digital Library - Supabase schema
-- =====================================================

create table if not exists public.buku (
  id bigint generated by default as identity primary key,
  judul text not null,
  stok int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  item_id bigint not null,
  qty int not null default 1,
  status text not null default 'sedang dipinjam' check (status in ('sedang dipinjam', 'sudah dikembalikan', 'terkena denda')),
  created_at timestamptz not null default now(),
  foreign key (item_id) references public.buku(id)
);

insert into public.buku (judul, stok)
select seed.judul, seed.stok
from (values
  ('Buku Sains Dasar', 10),
  ('Buku Fiksi Populer', 8),
  ('Buku Teknologi', 12)
) as seed(judul, stok)
where not exists (
  select 1
  from public.buku as existing
  where existing.judul = seed.judul
);

create or replace function public.proses_transaksi(
  p_customer_name text,
  p_item_id bigint,
  p_qty int
)
returns json
language plpgsql
security definer
as $$
declare
  v_stok int;
begin
  if p_qty is null or p_qty < 1 then
    raise exception 'Jumlah peminjaman harus lebih dari 0';
  end if;

  select stok into v_stok
  from public.buku
  where id = p_item_id;

  if v_stok is null then
    raise exception 'Buku tidak ditemukan';
  end if;

  if p_qty > v_stok then
    raise exception 'Stok tidak cukup';
  end if;

  update public.buku
  set stok = stok - p_qty
  where id = p_item_id;

  insert into public.transactions (customer_name, item_id, qty, status)
  values (p_customer_name, p_item_id, p_qty, 'sedang dipinjam');

  return json_build_object(
    'status', 'success',
    'message', 'Transaksi berhasil',
    'customer_name', p_customer_name,
    'item_id', p_item_id,
    'qty', p_qty
  );
end;
$$;

grant usage on schema public to anon, authenticated;
grant select, insert, update on public.buku to anon, authenticated;
grant select, insert, update on public.transactions to anon, authenticated;
grant execute on function public.proses_transaksi(text, bigint, int) to anon, authenticated;

alter table public.buku enable row level security;
alter table public.transactions enable row level security;

drop policy if exists buku_read_catalog on public.buku;
create policy buku_read_catalog on public.buku
  for select to anon, authenticated
  using (true);

drop policy if exists buku_write_authenticated on public.buku;
create policy buku_write_authenticated on public.buku
  for insert to authenticated
  with check (true);

drop policy if exists buku_update_authenticated on public.buku;
create policy buku_update_authenticated on public.buku
  for update to authenticated
  using (true)
  with check (true);

drop policy if exists transactions_read_authenticated on public.transactions;
create policy transactions_read_authenticated on public.transactions
  for select to authenticated
  using (true);

drop policy if exists transactions_insert_authenticated on public.transactions;
create policy transactions_insert_authenticated on public.transactions
  for insert to authenticated
  with check (true);

drop policy if exists transactions_update_authenticated on public.transactions;
create policy transactions_update_authenticated on public.transactions
  for update to authenticated
  using (true)
  with check (true);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'buku'
    ) then
      execute 'alter publication supabase_realtime add table public.buku';
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'transactions'
    ) then
      execute 'alter publication supabase_realtime add table public.transactions';
    end if;
  end if;
end;
$$;
